name: Package and release

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 50 # controls the length of the automated changelog

      - name: Package and release
        uses: BigWigsMods/packager@master